// This file translates the project's controlled PostgreSQL SQL asset subset
// into SQLite-compatible SQL.

package sqlite

import (
	"context"
	"regexp"
	"strings"

	"github.com/gogf/gf/v2/errors/gerror"

	"lina-core/pkg/dialect/internal/sqlscan"
	"lina-core/pkg/logger"
)

// unsupportedFeature describes one PostgreSQL-source construct that this
// SQLite translation path intentionally rejects instead of approximating.
type unsupportedFeature struct {
	keyword string
	pattern *regexp.Regexp
}

var (
	reCreateTable              = regexp.MustCompile(`(?is)^\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([^\s(]+)\s*\(`)
	reAlterTableAddColumn      = regexp.MustCompile(`(?is)^\s*ALTER\s+TABLE\s+\S+\s+ADD\s+COLUMN\b`)
	reCreateAnyCollation       = regexp.MustCompile(`(?is)^\s*CREATE\s+COLLATION\b`)
	reCommentOnSupportedObject = regexp.MustCompile(`(?is)^\s*COMMENT\s+ON\s+(?:TABLE|COLUMN)\b`)
	reCommentOnAnyObject       = regexp.MustCompile(`(?is)^\s*COMMENT\s+ON\b`)
	reDoBlock                  = regexp.MustCompile(`(?is)^\s*DO\s+\$[A-Za-z0-9_]*\$`)
	reCollateClause            = regexp.MustCompile(`(?i)\bCOLLATE\b`)
	reIdentityColumnType       = regexp.MustCompile(`(?i)\b(?:BIGINT|INT)\s+(?:NOT\s+NULL\s+)?GENERATED\s+ALWAYS\s+AS\s+IDENTITY(?:\s*\([^)]*\))?(?:\s+PRIMARY\s+KEY)?\b`)
	reIntegerTypes             = regexp.MustCompile(`(?i)\b(?:BIGINT|INT|SMALLINT)\b`)
	reTextTypes                = regexp.MustCompile(`(?i)\b(?:VARCHAR|CHAR)\s*\(\s*\d+\s*\)|\bTEXT\b`)
	reByteaType                = regexp.MustCompile(`(?i)\bBYTEA\b`)
	reTimestampType            = regexp.MustCompile(`(?i)(^|[^A-Za-z0-9_])TIMESTAMP\b`)
	reDecimalTypes             = regexp.MustCompile(`(?i)\b(?:DECIMAL|NUMERIC)(?:\s*\(\s*\d+\s*,\s*\d+\s*\))?`)
	reDoublePrecisionType      = regexp.MustCompile(`(?i)\bDOUBLE\s+PRECISION\b`)
	reNowFunc                  = regexp.MustCompile(`(?i)\bNOW\s*\(\s*\)`)
	reTimestampCast            = regexp.MustCompile(`(?i)::\s*TIMESTAMP\b`)
	reTimestampLiteralPrefix   = regexp.MustCompile(`(?i)\bTIMESTAMP\s*$`)
	reConstraintPrimaryKey     = regexp.MustCompile(`(?i)^\s*CONSTRAINT\s+\S+\s+PRIMARY\s+KEY\b`)
	reNamedInlineIndex         = regexp.MustCompile(`(?i)^(?:UNIQUE\s+)?(?:KEY|INDEX)\b`)
	reMySQLTableOption         = regexp.MustCompile(`(?i)\b(?:ENGINE|CHARSET)\s*=`)
	reDefaultCharset           = regexp.MustCompile(`(?i)\bDEFAULT\s+CHARSET\s*=`)
	reAddColumnIfNotExists     = regexp.MustCompile(`(?i)\bADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\b`)

	unsupportedFeatures = []unsupportedFeature{
		{keyword: "CREATE DATABASE", pattern: regexp.MustCompile(`(?i)\bCREATE\s+DATABASE\b`)},
		{keyword: "DROP DATABASE", pattern: regexp.MustCompile(`(?i)\bDROP\s+DATABASE\b`)},
		{keyword: "USE", pattern: regexp.MustCompile(`(?i)^\s*USE\b`)},
		{keyword: "CREATE EXTENSION", pattern: regexp.MustCompile(`(?i)\bCREATE\s+EXTENSION\b`)},
		{keyword: "CREATE FUNCTION", pattern: regexp.MustCompile(`(?i)\bCREATE\s+FUNCTION\b`)},
		{keyword: "CREATE PROCEDURE", pattern: regexp.MustCompile(`(?i)\bCREATE\s+PROCEDURE\b`)},
		{keyword: "CREATE TRIGGER", pattern: regexp.MustCompile(`(?i)\bCREATE\s+TRIGGER\b`)},
		{keyword: "CREATE TYPE", pattern: regexp.MustCompile(`(?i)\bCREATE\s+TYPE\b`)},
		{keyword: "CREATE SCHEMA", pattern: regexp.MustCompile(`(?i)\bCREATE\s+SCHEMA\b`)},
		{keyword: "CREATE DOMAIN", pattern: regexp.MustCompile(`(?i)\bCREATE\s+DOMAIN\b`)},
		{keyword: "MERGE", pattern: regexp.MustCompile(`(?i)\bMERGE\b`)},
		{keyword: "WITH RECURSIVE", pattern: regexp.MustCompile(`(?i)\bWITH\s+RECURSIVE\b`)},
		{keyword: "LATERAL", pattern: regexp.MustCompile(`(?i)\bLATERAL\b`)},
		{keyword: "TABLESAMPLE", pattern: regexp.MustCompile(`(?i)\bTABLESAMPLE\b`)},
		{keyword: "PARTITION OF", pattern: regexp.MustCompile(`(?i)\bPARTITION\s+OF\b`)},
		{keyword: "EXCLUDE USING", pattern: regexp.MustCompile(`(?i)\bEXCLUDE\s+USING\b`)},
		{keyword: "TRUNCATE", pattern: regexp.MustCompile(`(?i)\bTRUNCATE\b`)},
		{keyword: "JSONB", pattern: regexp.MustCompile(`(?i)\bJSONB\b`)},
		{keyword: "JSON", pattern: regexp.MustCompile(`(?i)\bJSON\b`)},
		{keyword: "JSON operator", pattern: regexp.MustCompile(`(?i)(->>|->|@>|<@|\?\s*')`)},
		{keyword: "ARRAY", pattern: regexp.MustCompile(`(?i)\bARRAY\b|\[\s*\]`)},
		{keyword: "TIMESTAMPTZ", pattern: regexp.MustCompile(`(?i)\bTIMESTAMPTZ\b`)},
		{keyword: "TIME WITH TIME ZONE", pattern: regexp.MustCompile(`(?i)\bTIME\s+WITH\s+TIME\s+ZONE\b`)},
		{keyword: "GENERATED ALWAYS AS", pattern: regexp.MustCompile(`(?i)\bGENERATED\s+ALWAYS\s+AS\s*\(`)},
		{keyword: "GENERATED BY DEFAULT AS IDENTITY", pattern: regexp.MustCompile(`(?i)\bGENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY\b`)},
		{keyword: "BIGSERIAL", pattern: regexp.MustCompile(`(?i)\bBIGSERIAL\b`)},
		{keyword: "SERIAL", pattern: regexp.MustCompile(`(?i)\bSERIAL\b`)},
		{keyword: "ON CONFLICT DO UPDATE", pattern: regexp.MustCompile(`(?i)\bON\s+CONFLICT\b[\s\S]*\bDO\s+UPDATE\b`)},
		{keyword: "AUTO_INCREMENT", pattern: regexp.MustCompile(`(?i)\bAUTO_INCREMENT\b`)},
		{keyword: "INSERT IGNORE", pattern: regexp.MustCompile(`(?i)\bINSERT\s+IGNORE\b`)},
		{keyword: "ON DUPLICATE KEY UPDATE", pattern: regexp.MustCompile(`(?i)\bON\s+DUPLICATE\s+KEY\s+UPDATE\b`)},
		{keyword: "UNSIGNED", pattern: regexp.MustCompile(`(?i)\bUNSIGNED\b`)},
		{keyword: "TINYINT", pattern: regexp.MustCompile(`(?i)\bTINYINT\b`)},
		{keyword: "DATETIME", pattern: regexp.MustCompile(`(?i)\bDATETIME\b`)},
		{keyword: "LONGTEXT", pattern: regexp.MustCompile(`(?i)\bLONGTEXT\b`)},
		{keyword: "MEDIUMTEXT", pattern: regexp.MustCompile(`(?i)\bMEDIUMTEXT\b`)},
		{keyword: "BLOB", pattern: regexp.MustCompile(`(?i)\b(?:BLOB|LONGBLOB|MEDIUMBLOB)\b`)},
		{keyword: "VARBINARY", pattern: regexp.MustCompile(`(?i)\bVARBINARY\b`)},
		{keyword: "ON UPDATE CURRENT_TIMESTAMP", pattern: regexp.MustCompile(`(?i)\bON\s+UPDATE\s+CURRENT_TIMESTAMP\b`)},
		{keyword: "backtick identifier", pattern: regexp.MustCompile("`")},
	}
)

// translateDDL translates a full PostgreSQL-source SQL asset into
// SQLite-compatible SQL.
func translateDDL(ctx context.Context, sourceName string, ddl string) (string, error) {
	var output []string
	for _, statement := range sqlscan.SplitStatements(ddl) {
		line := sqlscan.LineNumberForStatement(ddl, statement)
		if err := rejectUnsupportedSQL(sourceName, line, statement); err != nil {
			return "", err
		}
		translated, err := translateSQLiteStatement(ctx, sourceName, line, statement)
		if err != nil {
			return "", err
		}
		if translated == "" {
			continue
		}
		output = append(output, translated)
	}
	if len(output) == 0 {
		return "", nil
	}
	return strings.Join(output, "\n") + "\n", nil
}

// rejectUnsupportedSQL fails fast for PostgreSQL features outside the supported
// project SQL subset and for legacy MySQL syntax that must no longer be used as
// source SQL.
func rejectUnsupportedSQL(sourceName string, line int, statement string) error {
	if reCommentOnSupportedObject.MatchString(statement) {
		return nil
	}

	searchable := searchableSQL(statement)
	if reCreateAnyCollation.MatchString(searchable) {
		return unsupportedSQLError(sourceName, line, "CREATE COLLATION")
	}
	if reCommentOnAnyObject.MatchString(searchable) {
		return unsupportedSQLError(sourceName, line, "COMMENT ON")
	}
	if reCollateClause.MatchString(searchable) {
		return unsupportedSQLError(sourceName, line, "COLLATE")
	}
	if reDefaultCharset.MatchString(searchable) {
		return unsupportedSQLError(sourceName, line, "DEFAULT CHARSET")
	}
	if reMySQLTableOption.MatchString(searchable) {
		return unsupportedSQLError(sourceName, line, "ENGINE/CHARSET")
	}
	for _, feature := range unsupportedFeatures {
		if feature.pattern.MatchString(searchable) {
			return unsupportedSQLError(sourceName, line, feature.keyword)
		}
	}
	return nil
}

// unsupportedSQLError builds one source-aware translation failure.
func unsupportedSQLError(sourceName string, line int, keyword string) error {
	return gerror.Newf("unsupported PostgreSQL-source SQL in %s at line %d: %s", sourceName, line, keyword)
}

// translateSQLiteStatement translates one SQL statement.
func translateSQLiteStatement(ctx context.Context, sourceName string, line int, statement string) (string, error) {
	trimmed := strings.TrimSpace(statement)
	switch {
	case trimmed == "":
		return "", nil
	case reCommentOnSupportedObject.MatchString(trimmed):
		return "", nil
	case reDoBlock.MatchString(trimmed):
		logger.Debugf(ctx, "skip PostgreSQL procedural block during SQLite translation source=%s line=%d", sourceName, line)
		return "", nil
	case reCreateTable.MatchString(trimmed):
		return translateCreateTable(sourceName, line, trimmed)
	case reAlterTableAddColumn.MatchString(trimmed):
		return translateAlterTableAddColumn(trimmed) + ";", nil
	default:
		return translateCompatibleSQL(trimmed) + ";", nil
	}
}

// translateCreateTable translates one PostgreSQL CREATE TABLE statement.
func translateCreateTable(sourceName string, line int, statement string) (string, error) {
	openIndex := strings.Index(statement, "(")
	closeIndex := sqlscan.FindMatchingParen(statement, openIndex)
	if openIndex < 0 || closeIndex < 0 {
		return "", gerror.Newf("invalid CREATE TABLE statement in %s at line %d", sourceName, line)
	}

	header := strings.TrimSpace(statement[:openIndex])
	body := statement[openIndex+1 : closeIndex]
	suffix := strings.TrimSpace(statement[closeIndex+1:])
	if suffix != "" {
		return "", unsupportedSQLError(sourceName, line, firstSQLKeyword(suffix))
	}

	items := sqlscan.SplitTopLevelComma(body)
	identityColumns := identityColumnSet(items)
	columns := make([]string, 0, len(items))
	for _, item := range items {
		translated, err := translateCreateTableItem(sourceName, line, item, identityColumns)
		if err != nil {
			return "", err
		}
		if translated != "" {
			columns = append(columns, translated)
		}
	}
	if len(columns) == 0 {
		return "", gerror.Newf("CREATE TABLE statement in %s at line %d has no columns", sourceName, line)
	}
	return strings.TrimSpace(header) + " (\n    " + strings.Join(columns, ",\n    ") + "\n);", nil
}

// identityColumnSet returns column names that use PostgreSQL identity syntax.
func identityColumnSet(items []string) map[string]struct{} {
	identityColumns := make(map[string]struct{})
	for _, item := range items {
		trimmed := strings.TrimSpace(strings.TrimSuffix(item, ","))
		if trimmed == "" || isTableConstraint(trimmed) {
			continue
		}
		if reIdentityColumnType.MatchString(searchableSQL(trimmed)) {
			identityColumns[normalizedIdentifier(columnName(trimmed))] = struct{}{}
		}
	}
	return identityColumns
}

// translateCreateTableItem converts one comma-delimited CREATE TABLE item.
func translateCreateTableItem(
	sourceName string,
	line int,
	item string,
	identityColumns map[string]struct{},
) (string, error) {
	trimmed := strings.TrimSpace(strings.TrimSuffix(item, ","))
	if trimmed == "" {
		return "", nil
	}

	upper := strings.ToUpper(searchableSQL(trimmed))
	switch {
	case strings.HasPrefix(upper, "PRIMARY KEY"):
		if primaryKeyCoveredByIdentity(trimmed, identityColumns) {
			return "", nil
		}
		return translateCompatibleSQL(trimmed), nil
	case reConstraintPrimaryKey.MatchString(upper):
		if primaryKeyCoveredByIdentity(trimmed, identityColumns) {
			return "", nil
		}
		return translateCompatibleSQL(trimmed), nil
	case strings.HasPrefix(upper, "UNIQUE"),
		strings.HasPrefix(upper, "CHECK"),
		strings.HasPrefix(upper, "FOREIGN KEY"),
		strings.HasPrefix(upper, "CONSTRAINT"):
		return translateCompatibleSQL(trimmed), nil
	case reNamedInlineIndex.MatchString(upper):
		return "", unsupportedSQLError(sourceName, line, firstSQLKeyword(trimmed))
	default:
		return translateColumnDefinition(trimmed), nil
	}
}

// translateColumnDefinition converts one column definition.
func translateColumnDefinition(column string) string {
	name, definition := splitColumnDefinition(column)
	if name == "" || definition == "" {
		return translateTypeSQL(column)
	}
	return strings.TrimSpace(name + " " + translateTypeSQL(definition))
}

// translateAlterTableAddColumn converts PostgreSQL ADD COLUMN IF NOT EXISTS
// into SQLite's supported ADD COLUMN form for smoke-test initialization.
func translateAlterTableAddColumn(statement string) string {
	translated := rewriteOutsideQuotes(statement, func(segment string) string {
		return reAddColumnIfNotExists.ReplaceAllString(segment, "ADD COLUMN")
	})
	return translateTypeSQL(translated)
}

// translateCompatibleSQL performs non-type compatibility rewrites outside
// quoted strings and quoted identifiers.
func translateCompatibleSQL(sql string) string {
	translated := rewriteOutsideQuotes(sql, func(segment string) string {
		translated := reNowFunc.ReplaceAllString(segment, "CURRENT_TIMESTAMP")
		translated = reTimestampCast.ReplaceAllString(translated, "")
		translated = reTimestampLiteralPrefix.ReplaceAllString(translated, "")
		return translated
	})
	return strings.TrimSpace(translated)
}

// translateTypeSQL performs CREATE TABLE column type conversion outside quoted
// strings and quoted identifiers.
func translateTypeSQL(sql string) string {
	translated := rewriteOutsideQuotes(sql, func(segment string) string {
		translated := reIdentityColumnType.ReplaceAllString(segment, "INTEGER PRIMARY KEY AUTOINCREMENT")
		translated = reNowFunc.ReplaceAllString(translated, "CURRENT_TIMESTAMP")
		translated = reDoublePrecisionType.ReplaceAllString(translated, "REAL")
		translated = reIntegerTypes.ReplaceAllString(translated, "INTEGER")
		translated = reByteaType.ReplaceAllString(translated, "BLOB")
		translated = reTextTypes.ReplaceAllString(translated, "TEXT")
		translated = reTimestampType.ReplaceAllString(translated, "${1}DATETIME")
		translated = reDecimalTypes.ReplaceAllString(translated, "NUMERIC")
		return translated
	})
	return strings.TrimSpace(translated)
}

// splitColumnDefinition returns the column identifier and the rest of a column
// definition while preserving the original identifier quoting style.
func splitColumnDefinition(column string) (string, string) {
	trimmed := strings.TrimSpace(column)
	if trimmed == "" {
		return "", ""
	}
	if trimmed[0] == '"' {
		end := consumeQuotedSQL(trimmed, 0, '"')
		if end <= 0 || end > len(trimmed) {
			return "", trimmed
		}
		return trimmed[:end], strings.TrimSpace(trimmed[end:])
	}
	for index := 0; index < len(trimmed); index++ {
		if sqlscan.IsSQLWhitespace(trimmed[index]) {
			return trimmed[:index], strings.TrimSpace(trimmed[index:])
		}
	}
	return trimmed, ""
}

// primaryKeyCoveredByIdentity reports whether a table-level primary key repeats
// a single identity column already translated to SQLite's inline primary key.
func primaryKeyCoveredByIdentity(clause string, identityColumns map[string]struct{}) bool {
	columns := extractConstraintColumns(clause)
	if len(columns) != 1 {
		return false
	}
	_, ok := identityColumns[normalizedIdentifier(columns[0])]
	return ok
}

// extractConstraintColumns returns the top-level comma-separated columns in a
// table constraint.
func extractConstraintColumns(clause string) []string {
	openIndex := strings.Index(clause, "(")
	closeIndex := sqlscan.FindMatchingParen(clause, openIndex)
	if openIndex < 0 || closeIndex < 0 {
		return nil
	}
	return sqlscan.SplitTopLevelComma(clause[openIndex+1 : closeIndex])
}

// isTableConstraint reports whether an item is a table-level constraint rather
// than a column definition.
func isTableConstraint(item string) bool {
	upper := strings.ToUpper(searchableSQL(item))
	return strings.HasPrefix(upper, "PRIMARY KEY") ||
		strings.HasPrefix(upper, "UNIQUE") ||
		strings.HasPrefix(upper, "CHECK") ||
		strings.HasPrefix(upper, "FOREIGN KEY") ||
		strings.HasPrefix(upper, "CONSTRAINT") ||
		reNamedInlineIndex.MatchString(upper)
}

// columnName extracts the first identifier from one column definition.
func columnName(column string) string {
	fields := strings.Fields(column)
	if len(fields) == 0 {
		return ""
	}
	return fields[0]
}

// normalizedIdentifier compares quoted and unquoted SQL identifiers by their
// unquoted, lower-cased form.
func normalizedIdentifier(identifier string) string {
	trimmed := strings.TrimSpace(identifier)
	if len(trimmed) >= 2 {
		first := trimmed[0]
		last := trimmed[len(trimmed)-1]
		if (first == '"' && last == '"') || (first == '`' && last == '`') {
			trimmed = trimmed[1 : len(trimmed)-1]
		}
	}
	return strings.ToLower(trimmed)
}

// firstSQLKeyword returns a short diagnostic keyword for unsupported fragments.
func firstSQLKeyword(sql string) string {
	fields := strings.Fields(searchableSQL(sql))
	if len(fields) == 0 {
		return "unknown"
	}
	if len(fields) >= 2 {
		switch strings.ToUpper(fields[0]) {
		case "CREATE", "DROP", "ON", "WITH", "DEFAULT":
			return strings.ToUpper(fields[0] + " " + fields[1])
		}
	}
	return strings.ToUpper(fields[0])
}

// searchableSQL masks quoted strings and identifiers so unsupported syntax
// checks do not trigger on literal values or quoted column names.
func searchableSQL(sql string) string {
	return rewriteQuotedSQL(sql, func(quote byte, content string) string {
		if quote == '\'' || quote == '"' {
			return strings.Repeat(" ", len(content))
		}
		return content
	})
}

// rewriteOutsideQuotes applies rewrite to SQL text outside single-quoted
// strings and quoted identifiers.
func rewriteOutsideQuotes(sql string, rewrite func(string) string) string {
	var (
		builder strings.Builder
		segment strings.Builder
	)
	flushSegment := func() {
		if segment.Len() == 0 {
			return
		}
		builder.WriteString(rewrite(segment.String()))
		segment.Reset()
	}
	written := rewriteQuotedSQL(sql, func(quote byte, content string) string {
		if quote == 0 {
			segment.WriteString(content)
			return ""
		}
		flushSegment()
		builder.WriteString(content)
		return ""
	})
	if written != "" {
		segment.WriteString(written)
	}
	flushSegment()
	return builder.String()
}

// hasSQLKeywordAt reports whether keyword appears at index with identifier
// boundaries on both sides.
func hasSQLKeywordAt(sql string, index int, keyword string) bool {
	if index < 0 || index+len(keyword) > len(sql) {
		return false
	}
	if index > 0 && isSQLIdentifierByte(sql[index-1]) {
		return false
	}
	if !strings.EqualFold(sql[index:index+len(keyword)], keyword) {
		return false
	}
	next := index + len(keyword)
	return next >= len(sql) || !isSQLIdentifierByte(sql[next])
}

// skipSQLWhitespace returns the next non-whitespace byte index.
func skipSQLWhitespace(sql string, start int) int {
	for start < len(sql) && sqlscan.IsSQLWhitespace(sql[start]) {
		start++
	}
	return start
}

// isSQLIdentifierByte reports whether a byte can be part of a simple SQL
// identifier or keyword token.
func isSQLIdentifierByte(value byte) bool {
	return value == '_' ||
		(value >= '0' && value <= '9') ||
		(value >= 'A' && value <= 'Z') ||
		(value >= 'a' && value <= 'z')
}

// rewriteQuotedSQL walks SQL text and delegates each unquoted or quoted segment
// to rewrite. A quote value of zero identifies unquoted text.
func rewriteQuotedSQL(sql string, rewrite func(quote byte, content string) string) string {
	var (
		builder strings.Builder
		start   int
	)
	for i := 0; i < len(sql); i++ {
		switch sql[i] {
		case '\'', '"', '`':
			if start < i {
				builder.WriteString(rewrite(0, sql[start:i]))
			}
			quote := sql[i]
			end := consumeQuotedSQL(sql, i, quote)
			builder.WriteString(rewrite(quote, sql[i:end]))
			i = end - 1
			start = end
		}
	}
	if start < len(sql) {
		builder.WriteString(rewrite(0, sql[start:]))
	}
	return builder.String()
}

// consumeQuotedSQL returns the index after one quoted SQL string or identifier.
func consumeQuotedSQL(sql string, start int, quote byte) int {
	for i := start + 1; i < len(sql); i++ {
		current := sql[i]
		if quote == '\'' || quote == '"' {
			if sqlscan.ConsumeQuotedEscape(sql, &i, current, quote) {
				continue
			}
		} else if current == quote && i+1 < len(sql) && sql[i+1] == quote {
			i++
			continue
		}
		if current == quote {
			return i + 1
		}
	}
	return len(sql)
}
