// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	userapi "lina-core/api/user"
	i18nsvc "lina-core/internal/service/i18n"
	"lina-core/internal/service/menu"
	"lina-core/internal/service/role"
	usersvc "lina-core/internal/service/user"
	"lina-core/pkg/plugin/capability/orgcap/orgspi"
)

// ControllerV1 is the user controller.
type ControllerV1 struct {
	userSvc usersvc.Service // user service
	roleSvc role.Service    // role service
	menuSvc menu.Service    // menu service
	orgSvc  orgspi.Service  // organization capability service
	i18nSvc i18nsvc.Service // runtime translation service
}

// NewV1 creates and returns a new user controller instance.
func NewV1(
	userSvc usersvc.Service,
	roleSvc role.Service,
	menuSvc menu.Service,
	orgSvc orgspi.Service,
	i18nSvc i18nsvc.Service,
) userapi.IUserV1 {
	return &ControllerV1{
		userSvc: userSvc,
		roleSvc: roleSvc,
		menuSvc: menuSvc,
		orgSvc:  orgSvc,
		i18nSvc: i18nSvc,
	}
}
