// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sysinfo

import (
	"lina-core/api/sysinfo"
	i18nsvc "lina-core/internal/service/i18n"
	sysinfosvc "lina-core/internal/service/sysinfo"
)

// ControllerV1 is the system info controller.
type ControllerV1 struct {
	sysInfoSvc sysinfosvc.Service // system info service
	i18nSvc    i18nsvc.Service    // i18nSvc localizes project and component descriptions.
}

// NewV1 creates a sysinfo controller from explicit runtime-owned dependencies.
func NewV1(sysInfoSvc sysinfosvc.Service, i18nSvc i18nsvc.Service) sysinfo.ISysinfoV1 {
	return &ControllerV1{
		sysInfoSvc: sysInfoSvc,
		i18nSvc:    i18nSvc,
	}
}
